In [1]:
!pip3 install quandl

In [2]:
import pandas as pd
import numpy as np
import os
import quandl as quandl
import time
auth_tok='DyqJ9Yo7LyLz4ymydrno'

In [3]:
df=quandl.get("EOD/AAPL",authtoken=auth_tok)

In [4]:
df.head()

Open    High     Low    Close      Volume  Dividend  Split  \
Date                                                                       
2013-09-03  493.10  500.60  487.35  488.580  11854600.0       0.0    1.0   
2013-09-04  499.56  502.24  496.28  498.691  12322600.0       0.0    1.0   
2013-09-05  500.25  500.68  493.64  495.270   8441700.0       0.0    1.0   
2013-09-06  498.44  499.38  489.95  498.220  12840200.0       0.0    1.0   
2013-09-09  505.00  507.92  503.48  506.170  12167400.0       0.0    1.0   

             Adj_Open   Adj_High    Adj_Low  Adj_Close   Adj_Volume  
Date                                                                 
2013-09-03  15.619650  15.857223  15.437510  15.476472  331928800.0  
2013-09-04  15.824280  15.909173  15.720381  15.796753  345032800.0  
2013-09-05  15.846136  15.859757  15.636755  15.688388  236367600.0  
2013-09-06  15.788802  15.818578  15.519869  15.781833  359525600.0  
2013-09-09  15.996600  16.089095  15.948451  16.033661  340687200.0

In [5]:
df.shape

(1090, 12)

In [6]:
#High_low_percent
df['HL_PCT']=(df['Adj_High']-df['Adj_Low'])/df['Adj_Close']*100.0

#Percent Change
df['PCT_CHANGE']=(df['Adj_Close']-df['Adj_Open'])/df['Adj_Open']*100.0

In [7]:
df.head()

Open    High     Low    Close      Volume  Dividend  Split  \
Date                                                                       
2013-09-03  493.10  500.60  487.35  488.580  11854600.0       0.0    1.0   
2013-09-04  499.56  502.24  496.28  498.691  12322600.0       0.0    1.0   
2013-09-05  500.25  500.68  493.64  495.270   8441700.0       0.0    1.0   
2013-09-06  498.44  499.38  489.95  498.220  12840200.0       0.0    1.0   
2013-09-09  505.00  507.92  503.48  506.170  12167400.0       0.0    1.0   

             Adj_Open   Adj_High    Adj_Low  Adj_Close   Adj_Volume    HL_PCT  \
Date                                                                            
2013-09-03  15.619650  15.857223  15.437510  15.476472  331928800.0  2.711941   
2013-09-04  15.824280  15.909173  15.720381  15.796753  345032800.0  1.195129   
2013-09-05  15.846136  15.859757  15.636755  15.688388  236367600.0  1.421447   
2013-09-06  15.788802  15.818578  15.519869  15.781833  359525600.0  1.892738   
2013-09-09  15.996600  16.089095  15.948451  16.033661  340687200.0  0.877176   

            PCT_CHANGE  
Date                    
2013-09-03   -0.916650  
2013-09-04   -0.173953  
2013-09-05   -0.995502  
2013-09-06   -0.044138  
2013-09-09    0.231683

In [8]:
df.isnull().sum()

Open          0
High          0
Low           0
Close         0
Volume        0
Dividend      0
Split         0
Adj_Open      0
Adj_High      0
Adj_Low       0
Adj_Close     0
Adj_Volume    0
HL_PCT        0
PCT_CHANGE    0
dtype: int64

In [9]:
df.shape

(1090, 14)

In [10]:
# A variable for predicting 10 days out into the future
forecast_out = 10
#Create another column Future_Price shifted 10 units up
df['Future_Price'] = df[['Adj_Close']].shift(-forecast_out)
df_new=df.fillna(-99999)
print(df_new.tail(10))

              Open     High      Low   Close      Volume  Dividend  Split  \
Date                                                                        
2017-12-14  172.40  173.130  171.650  172.22  20476541.0       0.0    1.0   
2017-12-15  173.63  174.170  172.460  173.97  40169307.0       0.0    1.0   
2017-12-18  174.88  177.200  174.860  176.42  29421114.0       0.0    1.0   
2017-12-19  175.03  175.390  174.090  174.54  27436447.0       0.0    1.0   
2017-12-20  174.87  175.420  173.250  174.35  23475649.0       0.0    1.0   
2017-12-21  174.17  176.020  174.100  175.01  20949896.0       0.0    1.0   
2017-12-22  174.68  175.424  174.500  175.01  16349444.0       0.0    1.0   
2017-12-26  170.80  171.470  169.679  170.57  33185536.0       0.0    1.0   
2017-12-27  170.10  170.780  169.710  170.60  21498213.0       0.0    1.0   
2017-12-28  171.00  171.850  170.480  171.08  16480187.0       0.0    1.0   

             Adj_Open   Adj_High    Adj_Low  Adj_Close   Adj_Volume    HL_P

In [11]:
df1=df_new[['Adj_Close','Future_Price']]
df1.tail(10)

Adj_Close  Future_Price
Date                               
2017-12-14  41.430464      -99999.0
2017-12-15  41.851456      -99999.0
2017-12-18  42.440845      -99999.0
2017-12-19  41.988579      -99999.0
2017-12-20  41.942872      -99999.0
2017-12-21  42.101646      -99999.0
2017-12-22  42.101646      -99999.0
2017-12-26  41.033528      -99999.0
2017-12-27  41.040745      -99999.0
2017-12-28  41.156217      -99999.0

In [12]:
x = np.array(df1.drop(['Future_Price'],1))

#Remove the last '10' rows
x = x[:-forecast_out]
print(x)

[[15.47647246]
 [15.79675289]
 [15.68838781]
 ...
 [41.5387189 ]
 [41.30536882]
 [41.44249206]]


In [13]:
y = np.array(df1['Future_Price'])
# Get all of the y values except the last '10' rows
y = y[:-forecast_out]
print(y)

[14.42291424 14.71940567 14.96078011 ... 41.03352802 41.04074503
 41.15621723]


In [14]:
# Split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [15]:
from sklearn.linear_model import LinearRegression  ## Algorithm 
lr = LinearRegression()
# Train the model
model_train=lr.fit(x_train, y_train)

In [37]:
p=model_train.predict(x_test)
p

array([29.98869307, 28.41896805, 27.40699311, 22.07001968, 32.76256355,
       24.76751834, 27.59767949, 26.45526584, 16.69709283, 34.44953533,
       16.14657341, 25.70477343, 30.16998458, 29.79191506, 37.91953553,
       15.58850816, 19.13098028, 29.84992028, 29.04491364, 28.15795241,
       25.77143754, 29.26070466, 25.41415277, 18.59262678, 38.48724593,
       29.59284937, 25.71927356, 34.26498583, 38.61351494, 36.96062972,
       15.52924683, 32.79095578, 29.27107004, 40.118817  , 16.99611728,
       24.98732848, 15.72531358, 22.76975358, 15.78236838, 26.55139382,
       25.91570777, 28.30476545, 26.00320485, 36.80798217, 36.93389436,
       27.08402072, 41.49754226, 19.36471738, 27.90246363, 23.11433119,
       27.60920246, 21.72691517, 15.0050362 , 34.01182176, 25.81392375,
       21.2147285 , 29.08040287, 25.42493394, 37.1991635 , 17.34647986,
       15.81641212, 17.53529966, 27.04256799, 17.09355063, 17.08749053,
       28.0603338 , 41.6866486 , 40.67221538, 23.04201595, 22.45

In [16]:
lr_confidence = lr.score(x_test, y_test)
print("lr confidence: ", lr_confidence)

lr confidence:  0.9737577139732058


In [17]:
#lr_prediction = lr.predict(x_forecast)
#print(lr_prediction)
pred = model_train.predict(x_test) ## predict 20% of my data
pred

array([29.98869307, 28.41896805, 27.40699311, 22.07001968, 32.76256355,
       24.76751834, 27.59767949, 26.45526584, 16.69709283, 34.44953533,
       16.14657341, 25.70477343, 30.16998458, 29.79191506, 37.91953553,
       15.58850816, 19.13098028, 29.84992028, 29.04491364, 28.15795241,
       25.77143754, 29.26070466, 25.41415277, 18.59262678, 38.48724593,
       29.59284937, 25.71927356, 34.26498583, 38.61351494, 36.96062972,
       15.52924683, 32.79095578, 29.27107004, 40.118817  , 16.99611728,
       24.98732848, 15.72531358, 22.76975358, 15.78236838, 26.55139382,
       25.91570777, 28.30476545, 26.00320485, 36.80798217, 36.93389436,
       27.08402072, 41.49754226, 19.36471738, 27.90246363, 23.11433119,
       27.60920246, 21.72691517, 15.0050362 , 34.01182176, 25.81392375,
       21.2147285 , 29.08040287, 25.42493394, 37.1991635 , 17.34647986,
       15.81641212, 17.53529966, 27.04256799, 17.09355063, 17.08749053,
       28.0603338 , 41.6866486 , 40.67221538, 23.04201595, 22.45

In [18]:
df_final = pd.DataFrame({'Actual': y_test,'Pred': pred, 'Error': y_test - pred})
df_final

Actual       Pred     Error
0    29.296459  29.988693 -0.692234
1    28.933014  28.418968  0.514046
2    27.016736  27.406993 -0.390257
3    21.205089  22.070020 -0.864930
4    33.046431  32.762564  0.283867
..         ...        ...       ...
211  21.651914  20.761206  0.890707
212  34.154398  33.723167  0.431231
213  36.734029  36.924392 -0.190362
214  25.436144  24.349799  1.086345
215  17.281856  17.284284 -0.002428

[216 rows x 3 columns]

In [19]:
model_train.score(x_train,y_train)

0.9679343698110948

In [20]:
# Set x_forecast equal to the last 10 rows of the original data set from Adj. Close column
x_forecast = np.array(df1.drop(['Future_Price'],1))[-forecast_out:]
print(x_forecast)

[[41.43046371]
 [41.85145611]
 [42.44084548]
 [41.98857935]
 [41.94287161]
 [42.10164588]
 [42.10164588]
 [41.03352802]
 [41.04074503]
 [41.15621723]]


In [21]:
lr_prediction = lr.predict(x_forecast)
print(lr_prediction)

[41.57892124 41.99786097 42.58437658 42.13431562 42.08883073 42.24683086
 42.24683086 41.18392094 41.19110276 41.30601194]


In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
scale = StandardScaler()

In [24]:
df1['Adj_Close']

Date
2013-09-03    15.476472
2013-09-04    15.796753
2013-09-05    15.688388
2013-09-06    15.781833
2013-09-09    16.033661
                ...    
2017-12-21    42.101646
2017-12-22    42.101646
2017-12-26    41.033528
2017-12-27    41.040745
2017-12-28    41.156217
Name: Adj_Close, Length: 1090, dtype: float64

In [25]:
df2=df1.reset_index()

In [26]:
df2

Date  Adj_Close  Future_Price
0    2013-09-03  15.476472     14.422914
1    2013-09-04  15.796753     14.719406
2    2013-09-05  15.688388     14.960780
3    2013-09-06  15.781833     14.805882
4    2013-09-09  16.033661     15.541726
...         ...        ...           ...
1085 2017-12-21  42.101646 -99999.000000
1086 2017-12-22  42.101646 -99999.000000
1087 2017-12-26  41.033528 -99999.000000
1088 2017-12-27  41.040745 -99999.000000
1089 2017-12-28  41.156217 -99999.000000

[1090 rows x 3 columns]

In [31]:
t=scale.fit_transform(x)

In [32]:
t

array([[-1.66062923],
       [-1.61117497],
       [-1.62790754],
       ...,
       [ 2.36362235],
       [ 2.32759094],
       [ 2.34876404]])

In [33]:
scale.inverse_transform(t)

array([[15.47647246],
       [15.79675289],
       [15.68838781],
       ...,
       [41.5387189 ],
       [41.30536882],
       [41.44249206]])

In [34]:
from sklearn.metrics import mean_squared_error

In [39]:
a=mean_squared_error(y_test, p)
a

1.2607953650796162

In [40]:
round(a,2)

1.26